name: CI - Deploy Visual Thinker Playground
on:
  push:
    branches:
      - main
    paths:
      - "playground/**"
      - ".github/workflows/template-docker.yaml"
      - ".github/workflows/quality-gate-playground.yaml"
      - ".github/workflows/deploy-playground.yaml"

jobs:
  build-docker-x64:
    uses: ./.github/workflows/template-docker.yaml
    secrets: inherit
    with:
      runs-on: ubuntu-latest
      docker-file: playground/Dockerfile
      context: playground/        
      readme-file: ./README.md
      docker-repo-name: menloltd/visual-thinker-fe
      tags: menloltd/visual-thinker-fe:dev-${{ github.sha }}
      build-args: |
        GIT_COMMIT=menloltd/visual-thinker-fe:dev-${{ github.sha }}
        GIT_COMMIT_MESSAGE=${{ github.event.head_commit.message }}