name: build-docker-x64
on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
        default: "ubuntu-latest"
        description: "The runner to use for this job"
      docker-file:
        required: true
        type: string
        default: "./Dockerfile"
        description: "The docker file to use for this job"
      context:
        required: true
        type: string
        default: "."
        description: "The context to use for this job"
      readme-file:
        required: true
        type: string
        default: "./README.md"
        description: "The README file to use for this job"
      docker-repo-name:
        required: true
        type: string
        default: "cortex"
        description: "The name of the docker image"
      is_push:
        required: false
        type: boolean
        default: true
        description: "Whether to push the docker image"
      build-args:
        required: false
        type: string
        default: ""
        description: "The build args to use for docker build"
      tags:
        required: false
        type: string
        default: "menloltd/cortex:latest"
        description: "The tags to use for docker build and push"
      need_build_time_env_file:
        required: false
        type: boolean
        default: false
        description: "Whether to use the build-time environment file"
      dot_env_source_file:
        required: false
        type: string
        default: ".env"
        description: "The .env file to use for this job"
      dot_env_destination_file:
        required: false
        type: string
        default: ".env"
        description: "The .env file to use for this job"

jobs:
  build-docker-x64:
    runs-on: ${{ inputs.runs-on }}
    permissions:
      contents: write
    steps:
      - name: Getting the repo
        uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set .env file for build-time environment
        if: ${{ inputs.need_build_time_env_file }}
        continue-on-error: true
        run: |
          mv ${{ inputs.dot_env_source_file }} ${{ inputs.dot_env_destination_file }}
          cat ${{ inputs.dot_env_destination_file }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.docker-file }}
          push: ${{ inputs.is_push }}
          tags: ${{ inputs.tags }}
          build-args: ${{ inputs.build-args }}

      - name: Update Docker Hub overview
        if: ${{ inputs.is_push }}
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          README_CONTENT=$(cat ${{ inputs.readme-file }} | tr -d '\r' | sed ':a;N;$!ba;s/\n/\\n/g')
          JSON_PAYLOAD=$(printf '{"full_description": "%s"}' "$README_CONTENT")

          curl -X PATCH \
            -H "Content-Type: application/json" \
            -H "Authorization: JWT $(curl -s -H "Content-Type: application/json" -X POST -d '{"username": "'"$DOCKERHUB_USERNAME"'", "password": "'"$DOCKERHUB_TOKEN"'"}' https://hub.docker.com/v2/users/login/ | jq -r .token)" \
            -d "{\"full_description\": \"$JSON_PAYLOAD\"}" \
            https://hub.docker.com/v2/repositories/${{ inputs.docker-repo-name }}/